base_config: ../config.yaml

experiment:
  tag: minimal_full_model

model:
  use_hi: true
  use_attention: true
  attention_use_hi_bias: true

train:
  hi_supervision_weight: 0.10
  hi_rank_weight: 0.03
  hi_variance_weight: 0.10
